# version format
version: "{branch}-{build}"

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# Build on x64 only
platform: x64

install:
  - ps: Install-Product node 8 x64
  - appveyor-retry yarn install

build: off

test_script:
  - node --version
  - yarn test

on_finish:
  - del C:\projects\devhub.key
 