---
version: 2.1

orbs:
  # Code Coverage
  codecov: codecov/codecov@1.0.5
  # For Installing Browsers
  browser-tools: circleci/browser-tools@0.1.3
  # For Testing on windows
  win: circleci/windows@2.4.0

defaults: &defaults
  working_directory: ~/lightning-language-server
  docker:
    - image: circleci/node:12.15.0

jobs:
  # Default Job
  build-and-test-linux:
    <<: *defaults
    description: "Lint, Build, Test with Coverage"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-linux-{{ checksum "yarn.lock" }}

      # Build and Lint
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test_with_coverage

      # Cache the node_modules folder
      - save_cache:
          key: dependency-cache-linux-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      # Save the current workspace state for deployment to npm
      - persist_to_workspace:
          root: ~/lightning-language-server
          paths: .

      # Upload Coverage to CodeCov.io
      - codecov/upload:
          file: aura-language-server/coverage/*.json
          flags: frontend,aura
      - codecov/upload:
          file: lwc-language-server/coverage/*.json
          flags: frontend,lwc
      - codecov/upload:
          file: lightning-lsp-common/coverage/*.json
          flags: frontend,common

  build-and-test-win:
    description: "Run tests on windows"
    executor: win/default
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-win-{{ checksum "yarn.lock" }}
      # Build
      - run: yarn install --frozen-lockfile
      # Copy linked packages so we can run the tests correctly on windows
      - run:
          name: Setup workspace Symlinks for Windows
          command: yarn windowsCopySymlinks
      - run:
          name: Run tests on windows (Without coverage)
          command: yarn test    
      - save_cache:
          key: dependency-cache-win-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  # Publish to NPM
  deploy:
    <<: *defaults
    description: "Publish package to npmjs.org"
    steps:
      - attach_workspace:
          at: ~/lightning-language-server
      - add_ssh_keys:
          fingerprints:
            - "e4:06:a5:d3:f8:cf:25:5d:7b:e9:7a:4b:71:93:f9:6e"
#      - run: yarn install --frozen-lockfile
#      - run: yarn build
#      - run: git config user.email "kgray@salesforce.com"
#      - run: git config user.name "Kris Gray"
      - run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_PUBLISH_TOKEN}"
      - run: |
            yarn bump-versions
            yarn publish-lsp

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build-and-test-linux
      - build-and-test-win
      - deploy:
          requires:
            - build-and-test-linux
            - build-and-test-win
          filters:
            branches:
              only:
                - master
