name: Push to main

on:
  push:
    branches: [main]

jobs:
  tests:
      uses: salesforcecli/github-workflows/.github/workflows/unitTest.yml@main
  release:
    if: contains('refs/heads/main', github.ref)
    runs-on: ubuntu-latest
    container:
      image: node:lts
    needs:
    - tests
    steps:
    - uses: actions/download-artifact@v2
    - uses: actions/checkout@v3
    - name: Configuring GitHub
      run: |-
        git config credential.helper 'cache --timeout=120'
        git config user.email "$GH_EMAIL"
        git config user.name "Release Bot"
    - name: Bump package version
      run: |-
        yarn bump-versions << pipeline.parameters.version >>
        git add .
        export RELEASE_TAG="$(node -pe "require('./lerna.json').version")"
        git commit -m "Updated version $RELEASE_TAG [ci skip]"
    - name: Set .npmrc
      run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - run: yarn publish-lsp
    - run: git push origin main
    - name: Tag the release and push to repo
      run: |-
        export RELEASE_TAG="$(node -pe "require('./lerna.json').version")"
        git tag v${RELEASE_TAG}
        git push --tags