name: release

on:
  push:
    branches: [main]
  release:
    types: [released]
    inputs:
      tag:
        description: tag that needs to publish
        type: string
        required: true
jobs:
  tests:
    uses: salesforcecli/github-workflows/.github/workflows/unitTest.yml@main
  publish:
    runs-on: ubuntu-latest
    container:
      image: node:lts
    steps:
    - uses: actions/download-artifact@v2
    - uses: actions/checkout@v2
    - name: Configuring GitHub
      run: |-
        git config credential.helper 'cache --timeout=120'
        git config user.email "${{ secrets.GH_EMAIL }}"
        git config user.name "Release Bot"
    - name: Bump package version
      run: |-
        yarn bump-versions 'minor'
        git add .
        export RELEASE_TAG="$(node -pe "require('./lerna.json').version")"
        git commit -m "Updated version $RELEASE_TAG [ci skip]"
    - name: Set .npmrc
      run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    # - run: yarn publish-lsp
    - run: git push origin main
    - name: Tag the release and push to repo
      run: |-
        export RELEASE_TAG="$(node -pe "require('./lerna.json').version")"
        git tag v${RELEASE_TAG}
        git push --tags
    - uses: "./.github/workflows/slack_notify.yml@main"